const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const state={view:'home',zoom:1,history:[],future:[],projectType:'campaign'};
const views={home:$('#homeView'),projects:$('#projectsView'),templates:$('#templatesView'),assets:$('#assetsView'),team:$('#teamView'),editor:$('#editorView')};
function showView(name){Object.values(views).forEach(v=>v&&v.classList.remove('active-view'));views[name]?.classList.add('active-view');state.view=name;$$('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='projects'){const clone=$('.clone-projects');clone.innerHTML=$('#projectGrid').innerHTML;bindProjectCards(clone)}}
$$('.nav-item[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#allProjectsBtn').onclick=()=>showView('projects');
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__tt);window.__tt=setTimeout(()=>t.classList.remove('show'),2200)}
function openModal(){$('#projectModal').classList.remove('hidden');setTimeout(()=>$('#newProjectName').select(),80)}function closeModal(){$('#projectModal').classList.add('hidden')}
$('#newProjectBtn').onclick=openModal;$('#newProjectBtn2').onclick=openModal;$('#aiStartBtn').onclick=openModal;$('.modal-close').onclick=closeModal;$('#projectModal').addEventListener('click',e=>{if(e.target===$('#projectModal'))closeModal()});
$$('.modal-options button').forEach(b=>b.onclick=()=>{$$('.modal-options button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.projectType=b.dataset.type});
$$('.quick-card').forEach(b=>b.onclick=()=>{state.projectType=b.dataset.template==='video'?'video':b.dataset.template==='board'?'board':'campaign';openModal()});
$('#createProjectConfirm').onclick=()=>{const name=$('#newProjectName').value.trim()||'새 프로젝트';$('#editorProjectTitle').textContent=name;closeModal();showView('editor');toast('새 프로젝트가 생성되었습니다')};
function bindProjectCards(root=document){$$('.project-card',root).forEach(c=>c.onclick=e=>{if(e.target.closest('.more'))return;$('#editorProjectTitle').textContent=$('b',c)?.textContent||'프로젝트';showView('editor')})}bindProjectCards();$('#backHome').onclick=()=>showView('home');
$('#shareBtn').onclick=()=>{navigator.clipboard?.writeText(location.href).catch(()=>{});toast('공유 링크가 복사되었습니다')};$('#reviewBtn').onclick=()=>toast('검토 요청을 전송했습니다');$('#inviteBtn').onclick=()=>toast('팀원 초대 링크를 만들었습니다');
let drag=null;function snapshot(){return $$('.node').map(n=>n.outerHTML)}function saveSnapshot(){state.history.push(snapshot());if(state.history.length>30)state.history.shift();state.future=[]}function makeDraggable(node){node.addEventListener('pointerdown',e=>{if(e.button!==0)return;saveSnapshot();$$('.node').forEach(n=>n.classList.remove('selected'));node.classList.add('selected');const r=node.getBoundingClientRect(),c=$('#canvasGrid').getBoundingClientRect();drag={node,dx:e.clientX-r.left,dy:e.clientY-r.top,canvas:c};node.setPointerCapture?.(e.pointerId)});node.addEventListener('pointermove',e=>{if(!drag||drag.node!==node)return;let x=(e.clientX-drag.canvas.left-drag.dx)/state.zoom,y=(e.clientY-drag.canvas.top-drag.dy)/state.zoom;x=Math.max(0,Math.min(1160-node.offsetWidth,x));y=Math.max(0,Math.min(660-node.offsetHeight,y));node.style.left=x+'px';node.style.top=y+'px'});node.addEventListener('pointerup',()=>{drag=null;toast('변경사항 저장됨')})}$$('.node').forEach(makeDraggable);
function restore(s){if(!s)return;const grid=$('#canvasGrid');$$('.node',grid).forEach(n=>n.remove());s.forEach(html=>{const t=document.createElement('div');t.innerHTML=html;const n=t.firstElementChild;grid.appendChild(n);makeDraggable(n)})}
$('#undoBtn').onclick=()=>{if(!state.history.length)return toast('되돌릴 작업이 없습니다');state.future.push(snapshot());restore(state.history.pop());toast('되돌렸습니다')};$('#redoBtn').onclick=()=>{if(!state.future.length)return toast('다시 실행할 작업이 없습니다');state.history.push(snapshot());restore(state.future.pop());toast('다시 실행했습니다')};
function setZoom(z){state.zoom=Math.max(.5,Math.min(1.6,z));$('#canvasGrid').style.transform=`translate(-50%,-50%) scale(${state.zoom})`;$('#zoomLabel').textContent=Math.round(state.zoom*100)+'%'}$('#zoomIn').onclick=()=>setZoom(state.zoom+.1);$('#zoomOut').onclick=()=>setZoom(state.zoom-.1);
function showRight(type){$$('.right-tabs button').forEach(x=>x.classList.toggle('active',x.dataset.right===type));$('#aiPanel').classList.toggle('hidden',type!=='ai');$('#commentsPanel').classList.toggle('hidden',type!=='comments')}$$('.right-tabs button').forEach(b=>b.onclick=()=>showRight(b.dataset.right));
$$('.editor-tabs button').forEach(b=>b.onclick=()=>{$$('.editor-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.mode==='review')showRight('comments');toast(b.dataset.mode==='storyboard'?'스토리보드 보기로 전환했습니다':b.dataset.mode==='review'?'검토 댓글을 표시합니다':'Mainboard로 전환했습니다')});
$$('.tool').forEach(b=>b.onclick=()=>{$$('.tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.panel==='ai')showRight('ai');if(b.dataset.panel==='comment')showRight('comments');if(b.dataset.panel==='text')addText();if(b.dataset.panel==='shape')addShape()});
function addText(){saveSnapshot();const n=document.createElement('div');n.className='board-note node';n.dataset.node=Date.now();n.style.cssText='left:480px;top:270px;width:230px;height:105px;';n.innerHTML='<span class="tag blue">TEXT</span><h3 contenteditable="true">새 텍스트를 입력하세요</h3><p contenteditable="true">더블클릭해서 내용을 편집할 수 있습니다.</p>';$('#canvasGrid').appendChild(n);makeDraggable(n);toast('텍스트 요소를 추가했습니다')}
function addShape(){saveSnapshot();const n=document.createElement('div');n.className='node';n.dataset.node=Date.now();n.style.cssText='left:530px;top:260px;width:150px;height:110px;border-radius:18px;background:linear-gradient(135deg,#6657ff,#a55be8);';$('#canvasGrid').appendChild(n);makeDraggable(n);toast('도형을 추가했습니다')}
function esc(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function addAI(text,user=false){const w=document.createElement('div');w.className='ai-msg'+(user?' user-msg':'');w.innerHTML=user?`<p>${esc(text)}</p>`:`<span>✦</span><p>${text}</p>`;$('#aiChat').appendChild(w);w.scrollIntoView({behavior:'smooth',block:'end'})}function runAI(p){addAI(p,true);setTimeout(()=>{let a='프로젝트 문맥을 기준으로 작업안을 만들었습니다. ';if(/30초|스토리|영상/.test(p))a+='30초 기준 6개 장면으로 구성하고 각 장면에 목적·카피·비주얼 방향을 연결했습니다.';else if(/요약/.test(p))a+='현재 핵심 메시지는 “기획·제작·협업을 하나의 흐름으로 연결”이며, AI 자동화와 실시간 협업이 주요 차별점입니다.';else a+='선택한 보드 요소를 바탕으로 다음 작업을 이어갈 수 있습니다.';addAI(a);toast('AI 작업이 완료되었습니다')},450)}
$('#sendPrompt').onclick=()=>{const v=$('#aiPrompt').value.trim();if(!v)return;$('#aiPrompt').value='';runAI(v)};$('#aiPrompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#sendPrompt').click()}});$$('.ai-action').forEach(b=>b.onclick=()=>runAI({story:'선택한 자료로 30초 홍보영상 스토리보드를 만들어줘',copy:'현재 장면에 들어갈 짧은 카피를 작성해줘',summary:'현재 보드 핵심을 요약해줘'}[b.dataset.action]));
$('#addCommentBtn').onclick=()=>{const i=$('#commentInput'),v=i.value.trim();if(!v)return;const c=document.createElement('div');c.className='comment';c.innerHTML=`<div class="comment-user"><span>오</span><b>오창민</b><small>방금 전</small></div><p>${esc(v)}</p><div class="comment-actions"><button>답글</button><button class="resolve">해결</button></div>`;$('#commentsList').prepend(c);i.value='';bindResolve(c);toast('댓글을 등록했습니다')};function bindResolve(root=document){$$('.resolve',root).forEach(b=>b.onclick=()=>{b.closest('.comment').style.opacity='.45';b.textContent='해결됨';toast('댓글을 해결 처리했습니다')})}bindResolve();
$('#addScene').onclick=()=>{const count=$$('.scene-thumb').length+1,b=document.createElement('button');b.className='scene-thumb';b.innerHTML=`<span>${String(count).padStart(2,'0')}</span><div class="st-v st2">NEW</div>`;$('#addScene').before(b);toast(`Scene ${String(count).padStart(2,'0')}을 추가했습니다`)};
function addImage(file){if(!file.type.startsWith('image/'))return toast('이미지 파일을 선택해주세요');const r=new FileReader();r.onload=()=>{saveSnapshot();const n=document.createElement('div');n.className='board-image node image-node';n.dataset.node=Date.now();n.style.cssText='left:470px;top:220px;width:300px;height:205px;';n.innerHTML=`<img src="${r.result}" style="width:100%;height:160px;object-fit:cover;display:block"><div class="node-caption"><b>${esc(file.name)}</b><small>업로드 이미지</small></div>`;$('#canvasGrid').appendChild(n);makeDraggable(n);toast('이미지를 보드에 추가했습니다')};r.readAsDataURL(file)}$('#editorUpload').onchange=e=>{if(e.target.files[0])addImage(e.target.files[0])};
$('#assetUpload').onchange=e=>{[...e.target.files].forEach(file=>{const card=document.createElement('div');card.className='asset-card';card.innerHTML=`<div class="asset-preview doc">FILE</div><b>${esc(file.name)}</b><small>${(file.size/1024/1024).toFixed(1)}MB</small>`;$('#assetGrid').prepend(card)});toast(`${e.target.files.length}개 파일을 업로드 목록에 추가했습니다`)};
$('#globalSearch').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();$$('.project-card').forEach(c=>c.style.display=!q||c.textContent.toLowerCase().includes(q)?'':'none')});try{const saved=localStorage.getItem('metaflow_project');if(saved)$('#editorProjectTitle').textContent=saved}catch{}window.addEventListener('beforeunload',()=>{try{localStorage.setItem('metaflow_project',$('#editorProjectTitle').textContent)}catch{}});